all: MBASIC.EXE

MBASIC.EXE: MBASIC.C BASIC.C BASIC.H
        wcl -obmiler MBASIC.C BASIC.C

install: MBASIC.EXE
        COPY MBASIC.EXE ..\

clean:
        DEL *.BAK
        DEL *.OBJ
        DEL MBASIC.EXE
